import os
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from community_detector import CommunityDetector
from community_search import CommunitySearcher
from graph_builder import GraphBuilder
from graph_rag_service import GraphRAGService
from graph_search import GraphSearcher
from groq_service import GroqService

# Absolute path resolution for Vercel Serverless runtime
BASE_DIR = Path(__file__).resolve().parent

# Precomputed graph data lives in the repo and ships with the deployment.
# Generate/refresh this file locally by running `python build_graph.py`,
# then commit it. Do NOT rebuild the graph (i.e. call Groq) at request time.
GRAPH_DATA_PATH = BASE_DIR / "data" / "triples.json"


# ==========================================================
# Initialize GraphRAG System
# ==========================================================

def initialize_graph(app: FastAPI):
    """
    Fast startup path: load a precomputed graph from disk and run
    (cheap, local) community detection on it.

    IMPORTANT: This must NOT call the Groq API or write to disk.
    Those steps belong in build_graph.py, run offline/locally, with
    the output committed to the repo. This function runs on every
    cold start on Vercel, so it needs to be fast and side-effect-free.
    """

    if not GRAPH_DATA_PATH.exists():
        raise RuntimeError(
            f"Graph data not found at {GRAPH_DATA_PATH}. "
            "Run `python build_graph.py` locally and commit the output "
            "before deploying."
        )

    # Groq Service (still needed at runtime for answering user queries,
    # just not for building the graph)
    groq_service = GroqService()

    # Load precomputed graph (no LLM calls, no network I/O)
    graph_builder = GraphBuilder.from_json(GRAPH_DATA_PATH)
    graph_builder.print_statistics()

    # Community Detection (pure graph algorithm, cheap and local)
    community_detector = CommunityDetector(graph_builder.graph)
    communities = community_detector.detect()

    # Community Search
    community_searcher = CommunitySearcher(communities)

    # Graph Search
    graph_searcher = GraphSearcher(graph_builder.graph, communities)

    # GraphRAG Pipeline
    graph_rag_service = GraphRAGService(
        graph_searcher,
        community_searcher,
        groq_service,
    )

    # Global Application State
    app.state.groq_service = groq_service
    app.state.graph_builder = graph_builder
    app.state.graph_searcher = graph_searcher
    app.state.community_detector = community_detector
    app.state.community_searcher = community_searcher
    app.state.graph_rag_service = graph_rag_service
    app.state.communities = communities

    print("\n✓ Graph initialization completed (loaded from precomputed data).\n")


# ==========================================================
# Lifespan
# ==========================================================

@asynccontextmanager
async def lifespan(app: FastAPI):

    initialize_graph(app)

    yield

    print(
        "\nApplication shutting down...\n"
    )


# ==========================================================
# FastAPI Application
# ==========================================================

app = FastAPI(
    title="GraphRAG Game Assistant",
    version="1.0.0",
    lifespan=lifespan,
)


# ==========================================================
# Static Files
# ==========================================================

static_dir = BASE_DIR / "static"
if static_dir.exists():
    app.mount(
        "/static",
        StaticFiles(directory=str(static_dir)),
        name="static",
    )


# ==========================================================
# Templates
# ==========================================================

templates = Jinja2Templates(
    directory=str(BASE_DIR / "templates"),
)


# ==========================================================
# Graph Visualization (serves the HTML generated by build_graph.py)
# ==========================================================

GRAPH_HTML_PATH = BASE_DIR / "data" / "graph.html"


@app.get("/graph")
def get_graph_visualization():
    from fastapi.responses import FileResponse

    if not GRAPH_HTML_PATH.exists():
        return {"error": "Graph visualization not found. Run build_graph.py locally to generate it."}

    return FileResponse(GRAPH_HTML_PATH)


# ==========================================================
# API Routes
# ==========================================================

from api import router

app.include_router(router)